let g:gitgutter_realtime = 1
let g:gitgutter_eager = 1
let g:gitgutter_map_keys = 0
let g:gitgutter_diff_args= '-w'
let g:gitgutter_signs = 1
let g:gitgutter_highlight_lines = 0
let g:gitgutter_enabled = 1
let g:gitgutter_max_signs = 500
"let g:gitgutter_sign_column_always = 1
set signcolumn=yes
